---
name: Pipeline Test

on:
  - push

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/ansible/creator-ee:latest
    steps:
      - uses: actions/checkout@v4
      - run: ansible-lint
