---
name: Pipeline Test

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/ansible/creator-ee:latest
    steps:
      - uses: actions/checkout@v4
      - run: ansible-lint *.yml
      - run: yamllint *.yml
      - run: ansible-playbook --syntax-check *.yml
  moulecule:
    runs-on: ubuntu-latest
    container:
      image: quay.io/ansible/creator-ee:latest
    steps:
      - uses: actions/checkout@v4
      - run: cd roles/test_role && molecule test --all
